language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: MQIHNvaIh+9ELTKkuIKqrI8qZ4QqEyCgOyaCwD7JkTYzR3byGlySEbwMlsMYFOLCG/cgpbp/9CKPUGqZT4LK4T2jCOduDez5vSmS3M5mcPS9M7hYxRfWh05GtnnxrUIpodjQ1DEt27u4QUqT1SNQnXvH81tXj0HmGEO02wdKFiIHMJve8sv9vbpAkx+OnLz8W3rqztWeKiKlK1tAcfpXSqwQwsDSXSTcTgETU8+Un63CGSzM2HhzeodETxB3wsmeHMCwab6D2PnDmPDulRK56Xd4BlKSr1o1evy0L36I4ivcUMHnHzjCiCtAOU2UL93flyQh/I37wpr1B1A5DWD9l+Jkf4XqbUwmzU85JEcogPIoAyWrYZ7dp/pH2qlHVsJO1DCktM/j0yT24GKClfBajoFKkC1xttm7ztA0Jjqe0cGTqVx5zf9FX48Xe1bzmUaOtbFIttUrdwPOlxP1FQHmWv/ZXCbd2ysQ+vjTWZnBZOIpwYgttL5loYfXfk+EIoz8dTNf6O5jK9Q8mbG7/4o8dF/QitQi8COab09g3L4YAPbvlv7ygUHG48lWlUlwkHJdglWoOAtSgNv/fxQASfoeBRExlvUOB0vRmfoHKwUvkLWGs4ufxxH1KL4NQkfQjWq5Qibk9UvhKQPJJR7QZ4vGpJRAuXfKcrYX0rR91PP9rEY=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-tmdb-movie*"
  - "dist/oem_database_anidb_tmdb_movie*"
  on:
    repo: OpenEntityMap/oem-database-anidb-tmdb-movie
    tags: true
